package main

import (
	"bufio"
	"fmt"
	"os"

	goflag "flag"

	"github.com/childe/healer"
	"github.com/golang/glog"
	flag "github.com/spf13/pflag"
)

var (
	config    = healer.DefaultProducerConfig()
	topic     = flag.String("topic", "", "REQUIRED: The topic write message to.")
	partition = flag.Int("partition", 0, "The partition to consume from.")
)

func init() {
	flag.CommandLine.AddGoFlagSet(goflag.CommandLine)

	flag.StringVar(&config.BootstrapServers, "bootstrap.servers", config.BootstrapServers, "The list of hostname and port of the server to connect to.")
	flag.StringVar(&config.CompressionType, "compression.type", config.CompressionType, "The compression type for all data generated by the producer. The default is none (i.e. no compression). Valid values are none, gzip, snappy, or lz4. Compression is of full batches of data, so the efficacy of batching will also impact the compression ratio (more batching means better compression).")
	flag.IntVar(&config.ConnectionsMaxIdleMS, "connections.max.idle.ms", config.ConnectionsMaxIdleMS, "Close idle connections after the number of milliseconds specified by this config.")
}

func main() {
	flag.Parse()

	if *topic == "" {
		flag.PrintDefaults()
		os.Exit(4)
	}

	simpleProducer := healer.NewSimpleProducer(*topic, int32(*partition), config)

	if simpleProducer == nil {
		fmt.Println("could not create simpleProducer")
		os.Exit(5)
	}

	var (
		err        error
		scanner    = bufio.NewScanner(os.Stdin)
		returnCode = 0
	)

	for scanner.Scan() {
		line := scanner.Bytes()
		if err = simpleProducer.AddMessage(nil, line); err != nil {
			glog.Errorf("add message error: %s", err)
		}
	}

	if err := scanner.Err(); err != nil {
		glog.Errorf("scan stdin error: %v", err)
		returnCode = 5
	}

	simpleProducer.Close()
	glog.Flush()
	os.Exit(returnCode)
}
