name: Build and Push Docker Image

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.23

      - name: Install swag
        run: go install github.com/swaggo/swag/cmd/swag@latest

      - name: Test
        run: make test

      - name: Build
        run: make build && mv healer docker/

      - name: Build the Docker image
        run: docker build -t rmself/healer:${GITHUB_REF_NAME} docker

      - name: Log in to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker image
        run: docker push rmself/healer:${GITHUB_REF_NAME}

      - name: Tag latest
        run: docker tag rmself/healer:${GITHUB_REF_NAME} rmself/healer

      - name: Push Docker image
        run: docker push rmself/healer
